'use client';
import {useEffect,useState} from 'react';
type G={id:string,nome:string,classe:'QS'|'QR',unidade:{sigla:string}};
type E={generoId:string,quantidade:number|string};
type Item={generoId:string,quantidade:string};
const vazio=():Item=>({generoId:'',quantidade:''});
const destinos=[['CAFE_DA_MANHA','Café da manhã'],['ALMOCO','Almoço'],['JANTAR','Jantar'],['CEIA','Ceia'],['OUTRO','Outro']] as const;
export default function SaidaClient(){
 const[classe,setClasse]=useState<'QS'|'QR'>('QS');const[generos,setGeneros]=useState<G[]>([]);const[saldos,setSaldos]=useState<Record<string,number>>({});const[itens,setItens]=useState<Item[]>([vazio()]);const[destino,setDestino]=useState('ALMOCO');const[data,setData]=useState(()=>new Date().toISOString().slice(0,10));const[observacao,setObservacao]=useState('');const[msg,setMsg]=useState('');const[busy,setBusy]=useState(false);const[revisar,setRevisar]=useState(false);
 async function carregar(){const[g,e]=await Promise.all([fetch('/api/generos?classe='+classe).then(r=>r.json()),fetch('/api/estoque?classe='+classe).then(r=>r.json())]);setGeneros(g);const s:Record<string,number>={};for(const x of e as E[])s[x.generoId]=(s[x.generoId]||0)+Number(x.quantidade);setSaldos(s)}
 useEffect(()=>{carregar();setItens([vazio()]);setRevisar(false);setMsg('')},[classe]);
 const gs=(id:string)=>generos.find(g=>g.id===id);const update=(i:number,k:keyof Item,v:string)=>setItens(a=>a.map((x,n)=>n===i?{...x,[k]:v}:x));
 function validar(){const vistos=new Set<string>();for(const i of itens){const g=gs(i.generoId);if(!g)return 'Selecione o gênero em todos os itens.';if(vistos.has(i.generoId))return `${g.nome} foi adicionado mais de uma vez.`;vistos.add(i.generoId);const q=Number(i.quantidade);if(!(q>0))return `${g.nome}: informe uma quantidade válida.`;if(q>(saldos[i.generoId]||0))return `${g.nome}: solicitado ${q.toLocaleString('pt-BR')} ${g.unidade.sigla}, mas há ${(saldos[i.generoId]||0).toLocaleString('pt-BR')} ${g.unidade.sigla} disponíveis.`;}return ''}
 async function confirmar(){const e=validar();if(e){setMsg(e);return}setBusy(true);setMsg('');const r=await fetch('/api/saidas',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({classe,destino,data,observacao:observacao||undefined,itens:itens.map(i=>({generoId:i.generoId,quantidade:Number(i.quantidade)}))})});const j=await r.json();setBusy(false);if(!r.ok){setMsg(j.error||'Não foi possível concluir a saída.');await carregar();return}setMsg(`Saída nº ${j.numero} confirmada e estoque atualizado.`);setItens([vazio()]);setObservacao('');setRevisar(false);await carregar()}
 return <>
  <div className="tabs"><button className={'tab '+(classe==='QS'?'active':'')} onClick={()=>setClasse('QS')}>QS</button><button className={'tab '+(classe==='QR'?'active':'')} onClick={()=>setClasse('QR')}>QR</button></div>
  {msg&&<div className={msg.includes('confirmada')?'success':'error'}>{msg}</div>}
  <div className="card"><h2>Destino da saída</h2><div className="grid"><label>Refeição/destino<select value={destino} onChange={e=>setDestino(e.target.value)}>{destinos.map(([v,n])=><option value={v} key={v}>{n}</option>)}</select></label><label>Data<input type="date" value={data} onChange={e=>setData(e.target.value)}/></label></div><label>Observação<input value={observacao} onChange={e=>setObservacao(e.target.value)}/></label></div>
  <div className="card"><div className="top"><h2>Gêneros</h2><button className="linkbtn" onClick={()=>setItens(a=>[...a,vazio()])}>+ Adicionar gênero</button></div>{itens.map((i,n)=>{const g=gs(i.generoId);return <div className="itembox" key={n}><div className="top"><b>Item {n+1}</b>{itens.length>1&&<button className="dangerlink" onClick={()=>setItens(a=>a.filter((_,x)=>x!==n))}>Remover</button>}</div><div className="grid"><label>Gênero<select value={i.generoId} onChange={e=>update(n,'generoId',e.target.value)}><option value="">Selecione...</option>{generos.filter(x=>(saldos[x.id]||0)>0).map(x=><option key={x.id} value={x.id}>{x.nome} — {(saldos[x.id]||0).toLocaleString('pt-BR')} {x.unidade.sigla}</option>)}</select></label><label>Quantidade {g&&`(${g.unidade.sigla})`}<input type="number" min="0" step="0.001" value={i.quantidade} onChange={e=>update(n,'quantidade',e.target.value)}/></label></div>{g&&<span className="muted">Disponível: {(saldos[g.id]||0).toLocaleString('pt-BR')} {g.unidade.sigla}. O sistema utilizará primeiro o lote válido com vencimento mais próximo, quando houver.</span>}</div>})}</div>
  <div className="card"><div className="top"><div><b>{destinos.find(x=>x[0]===destino)?.[1]} · {classe}</b><p className="muted">{itens.length} item(ns) na saída</p></div>{!revisar?<button className="btn" onClick={()=>{const e=validar();if(e)setMsg(e);else{setMsg('');setRevisar(true)}}}>Revisar saída</button>:<div className="actions"><button className="linkbtn" onClick={()=>setRevisar(false)}>Voltar e editar</button><button className="btn" disabled={busy} onClick={confirmar}>{busy?'Confirmando...':'Confirmar saída'}</button></div>}</div>{revisar&&<p className="muted">Confira destino, gêneros e quantidades. A confirmação fará a baixa do estoque e registrará os lotes/localizações utilizados.</p>}</div>
 </>
}
