import {z} from 'zod';import {prisma} from '@/lib/prisma';import {requireAdmin} from '@/lib/guard';
const item=z.object({itemCompraId:z.string(),localId:z.string(),quantidade:z.coerce.number().positive(),valorUnitarioReal:z.coerce.number().nonnegative().optional().nullable(),lote:z.string().optional().nullable(),validade:z.string().optional().nullable()});
const body=z.object({data:z.string(),origem:z.string().optional(),documento:z.string().optional(),observacao:z.string().optional(),itens:z.array(item).min(1)});
export async function POST(req:Request,{params}:{params:Promise<{id:string}>}){const g=await requireAdmin();if(g.error)return g.error;const {id}=await params;const p=body.safeParse(await req.json());if(!p.success)return Response.json({error:'Revise os dados do recebimento vinculado e informe ao menos um item.'},{status:400});
try{const result=await prisma.$transaction(async tx=>{const compra=await tx.compraQR.findUnique({where:{id},include:{itens:{include:{genero:true,recebimentos:true}}}});if(!compra)throw new Error('COMPRA_NAO_ENCONTRADA');if(compra.status==='CANCELADA'||compra.status==='RECEBIDA')throw new Error('COMPRA_FECHADA');
const recebidas=new Map(compra.itens.map(i=>[i.id,i.recebimentos.reduce((a,r)=>a+Number(r.quantidade),0)]));for(const i of p.data.itens){const ci=compra.itens.find(x=>x.id===i.itemCompraId);if(!ci)throw new Error('ITEM_INVALIDO');const pend=Number(ci.quantidade)-(recebidas.get(ci.id)||0);if(i.quantidade>pend+1e-9)throw new Error(`EXCESSO:${ci.genero.nome}:${pend}`);if(ci.genero.controlaLote&&!i.lote)throw new Error(`LOTE:${ci.genero.nome}`);if(ci.genero.controlaValidade&&!i.validade)throw new Error(`VALIDADE:${ci.genero.nome}`)}
const rec=await tx.recebimento.create({data:{classe:'QR',data:new Date(p.data.data),origem:p.data.origem||compra.fornecedor,documento:p.data.documento,observacao:p.data.observacao||`Recebimento vinculado à compra QR nº ${compra.numero}`,criadoPorId:g.user!.id}});const vinc=await tx.recebimentoCompraQR.create({data:{compraId:compra.id,recebimentoId:rec.id}});
for(const i of p.data.itens){const ci=compra.itens.find(x=>x.id===i.itemCompraId)!;let loteId:string|undefined;if(ci.genero.controlaLote&&i.lote){const l=await tx.lote.upsert({where:{generoId_numero:{generoId:ci.generoId,numero:i.lote!}},update:{validade:i.validade?new Date(i.validade):undefined},create:{generoId:ci.generoId,numero:i.lote!,validade:i.validade?new Date(i.validade):undefined}});loteId=l.id}await tx.itemRecebimento.create({data:{recebimentoId:rec.id,generoId:ci.generoId,localId:i.localId,loteId,quantidade:i.quantidade,valorUnitario:i.valorUnitarioReal??ci.valorUnitarioEmpenhado??undefined,itemCompraQRId:ci.id}});await tx.itemRecebimentoCompraQR.create({data:{vinculoId:vinc.id,itemCompraId:ci.id,generoId:ci.generoId,quantidade:i.quantidade,valorUnitarioReal:i.valorUnitarioReal??ci.valorUnitarioEmpenhado??undefined}});await tx.estoqueLocal.upsert({where:{generoId_localId_loteId:{generoId:ci.generoId,localId:i.localId,loteId:loteId!}},update:{quantidade:{increment:i.quantidade}},create:{generoId:ci.generoId,localId:i.localId,loteId,quantidade:i.quantidade}});await tx.movimentacaoEstoque.create({data:{tipo:'RECEBIMENTO',classe:'QR',generoId:ci.generoId,loteId,localDestinoId:i.localId,quantidade:i.quantidade,valorUnitario:i.valorUnitarioReal??ci.valorUnitarioEmpenhado??undefined,referenciaTipo:'RecebimentoCompraQR',referenciaId:vinc.id,observacao:`Compra QR nº ${compra.numero}`,usuarioId:g.user!.id}})}
const all=await tx.itemRecebimentoCompraQR.groupBy({by:['itemCompraId'],where:{vinculo:{compraId:compra.id}},_sum:{quantidade:true}});const totalEmp=compra.itens.reduce((a,i)=>a+Number(i.quantidade),0),totalRec=all.reduce((a,x)=>a+Number(x._sum.quantidade||0),0);const status=totalRec>=totalEmp-1e-9?'RECEBIDA':'PARCIALMENTE_RECEBIDA';await tx.compraQR.update({where:{id:compra.id},data:{status}});return {recebimentoNumero:rec.numero,status,totalRecebido:totalRec,totalEmpenhado:totalEmp}});return Response.json(result)}catch(e:any){const m=String(e.message);if(m==='COMPRA_NAO_ENCONTRADA')return Response.json({error:'Compra QR não encontrada.'},{status:404});if(m==='COMPRA_FECHADA')return Response.json({error:'Esta compra QR já está recebida ou cancelada e não aceita novo recebimento.'},{status:400});if(m==='ITEM_INVALIDO')return Response.json({error:'Há item que não pertence à compra selecionada.'},{status:400});if(m.startsWith('EXCESSO:')){const[,nome,pend]=m.split(':');return Response.json({error:`${nome}: quantidade acima do saldo pendente (${Number(pend).toLocaleString('pt-BR',{maximumFractionDigits:3})}).`},{status:400})}if(m.startsWith('LOTE:'))return Response.json({error:`${m.slice(5)}: informe o lote para prosseguir.`},{status:400});if(m.startsWith('VALIDADE:'))return Response.json({error:`${m.slice(9)}: informe a validade para prosseguir.`},{status:400});throw e}}
